<?php

return [ 
    [ 'id' => '1', 'name' => 'Carpintaria' ],
    [ 'id' => '2', 'name' => 'Construção Civil' ],
    [ 'id' => '3', 'name' => 'Construção de Móveis' ],
    [ 'id' => '4', 'name' => 'Construção de Portas' ],
    [ 'id' => '5', 'name' => 'Elétrica' ],
    [ 'id' => '6', 'name' => 'Hidráulica' ],
    [ 'id' => '7', 'name' => 'Instalação de Bombas' ],
    [ 'id' => '8', 'name' => 'Instalação de Tubulações' ],
    [ 'id' => '9', 'name' => 'Instalação de Vidros' ],
    [ 'id' => '10', 'name' => 'Instalação Elétrica' ],
    [ 'id' => '11', 'name' => 'Manutenção de Bombas' ],
    [ 'id' => '12', 'name' => 'Manutenção de Veículos' ],
    [ 'id' => '13', 'name' => 'Manutenção Elétrica' ],
    [ 'id' => '14', 'name' => 'Mecânica' ],
    [ 'id' => '15', 'name' => 'Obra de Alvenaria' ],
    [ 'id' => '16', 'name' => 'Pintura' ],
    [ 'id' => '17', 'name' => 'Pintura de Parede' ],
    [ 'id' => '18', 'name' => 'Pintura de Teto' ],
    [ 'id' => '19', 'name' => 'Reformas' ],
    [ 'id' => '20', 'name' => 'Reparo de Motores' ],
    [ 'id' => '21', 'name' => 'Reparo de Móveis' ],
    [ 'id' => '22', 'name' => 'Reparo de Portas' ],
    [ 'id' => '23', 'name' => 'Reparo de Vidros' ],
    [ 'id' => '24', 'name' => 'Serralheria' ],
    [ 'id' => '25', 'name' => 'Vidraceiro' ],
];
