@startuml Cadastrar Prestador
title Cadastrar Prestador
left to right direction
actor Usuário
actor Sistema
actor Admin

rectangle "Processo de Cadastrar Prestador" {
    Usuário --> (Acessar Página Inicial)
    Usuário --> (Visualizar Planos)
    Usuário --> (Demonstra Interesse em Cadastrar-se)
    Usuário --> (Preencher Formulário de Pré-Cadastro)
    Sistema --> (Validar Dados)
    Sistema --> (Criar Novo Registro de Prestador) : Dados Válidos
    Sistema --> (Enviar E-mail de Confirmação)
    Sistema --> (Autenticar Novo Prestador)
    Sistema --> (Direcionar para Página Inicial do Prestador)
    Sistema --> (Notificar Prestador para Escolher Planos)
    Sistema --> (Direcionar para Tela de Edição e Pagamento)
}

rectangle "Fluxos Alternativos" {
    Sistema --> Usuário : "E-mail já cadastrado"
    Sistema --> Usuário : "Erro na validação dos dados"
}

rectangle "Pós-condições" {
    Sistema --> Admin : "Notificação de Novo Prestador Cadastrado"
}
@enduml
