openapi: 3.0.0
info:
  title: Easy Budget Platform - Budget API
  description: API for managing budgets in the Easy Budget Platform
  version: 1.0.0
servers:
  - url: https://api.easybudget.net.br/v1
    description: Production server
  - url: http://localhost:8000/api/v1
    description: Development server

security:
  - bearerAuth: []

paths:
  /budgets:
    post:
      summary: Create a new budget
      description: Creates a new budget for a customer with line items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customer_id
                - items
                - due_date
              properties:
                customer_id:
                  type: integer
                  description: ID of the customer
                description:
                  type: string
                  description: Budget description
                due_date:
                  type: string
                  format: date
                  description: Due date for the budget
                discount:
                  type: number
                  format: float
                  default: 0
                  description: Discount amount
                payment_terms:
                  type: string
                  description: Payment terms
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - product_id
                      - quantity
                      - unit_price
                    properties:
                      product_id:
                        type: integer
                        description: ID of the product/service
                      quantity:
                        type: integer
                        description: Quantity
                      unit_price:
                        type: number
                        format: float
                        description: Unit price
                      description:
                        type: string
                        description: Item description
      responses:
        "201":
          description: Budget created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      code:
                        type: string
                      total:
                        type: number
                        format: float
                      status:
                        type: string
                  message:
                    type: string
                    example: "Budget created successfully"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: object
                  message:
                    type: string
        "401":
          description: Unauthorized
        "403":
          description: Forbidden - insufficient permissions
        "422":
          description: Unprocessable entity - business logic error

  /budgets/{id}:
    get:
      summary: Get budget details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Budget details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      code:
                        type: string
                      customer:
                        type: object
                      items:
                        type: array
                        items:
                          type: object
                      total:
                        type: number
                        format: float
                      status:
                        type: string
        "404":
          description: Budget not found

    put:
      summary: Update budget
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                due_date:
                  type: string
                  format: date
                discount:
                  type: number
                  format: float
                payment_terms:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                      unit_price:
                        type: number
                        format: float
                      description:
                        type: string
      responses:
        "200":
          description: Budget updated successfully
        "400":
          description: Validation error
        "404":
          description: Budget not found

    delete:
      summary: Delete budget
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Budget deleted successfully
        "404":
          description: Budget not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        errors:
          type: object
