openapi: 3.0.3
info:
  title: Easy Budget Laravel - Google OAuth API
  description: API para autenticação via Google OAuth 2.0
  version: 1.0.0
  contact:
    name: API Support
    email: support@easybudget.com.br

servers:
  - url: https://api.easybudget.com.br/v1
    description: Production server
  - url: https://dev.easybudget.com.br/v1
    description: Development server
  - url: http://localhost:8000/v1
    description: Local development server

components:
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Erro de autenticação"
        errors:
          type: object
          additionalProperties: true
        error_code:
          type: string
          example: "OAUTH_FAILED"

    Success:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Operação realizada com sucesso"
        data:
          type: object
          additionalProperties: true

    GoogleAuthRequest:
      type: object
      properties:
        redirect_url:
          type: string
          description: URL para redirecionar após login bem-sucedido
          example: "/dashboard"
          maxLength: 255

    GoogleUnlinkRequest:
      type: object
      properties:
        confirm:
          type: boolean
          description: Confirmação para desvincular conta Google
          example: true

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token de autenticação JWT

paths:
  /auth/google:
    post:
      summary: Iniciar autenticação Google
      description: |
        Inicia o fluxo de autenticação OAuth 2.0 com Google.
        Redireciona o usuário para a página de autorização do Google.
      tags:
        - Authentication
        - OAuth
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GoogleAuthRequest"
      responses:
        "302":
          description: Redirecionamento para Google OAuth
          headers:
            Location:
              schema:
                type: string
              example: "https://accounts.google.com/oauth/authorize?client_id=...&redirect_uri=...&state=..."
        "400":
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/google/callback:
    get:
      summary: Processar callback do Google
      description: |
        Endpoint para processar o retorno do Google após autenticação.
        Troca o código de autorização por tokens e cria/vincula conta do usuário.
      tags:
        - Authentication
        - OAuth
      parameters:
        - name: code
          in: query
          required: true
          description: Código de autorização retornado pelo Google
          schema:
            type: string
          example: "4/0AX4XfWi..."
        - name: state
          in: query
          required: true
          description: Token CSRF para validação de segurança
          schema:
            type: string
          example: "csrf_token_abc123"
        - name: error
          in: query
          required: false
          description: Erro retornado pelo Google (se houver)
          schema:
            type: string
          example: "access_denied"
      responses:
        "302":
          description: Redirecionamento após processamento
          headers:
            Location:
              schema:
                type: string
              examples:
                success:
                  summary: Login bem-sucedido
                  value: "/dashboard"
                error:
                  summary: Erro de autenticação
                  value: "/login?error=oauth_failed"
        "400":
          description: Parâmetros inválidos ou erro do Google
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Erro interno durante processamento
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/google/unlink:
    post:
      summary: Desvincular conta Google
      description: |
        Remove a vinculação entre a conta do usuário e o Google OAuth.
        O usuário continuará com sua conta normal, apenas sem integração Google.
      tags:
        - Authentication
        - OAuth
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GoogleUnlinkRequest"
      responses:
        "200":
          description: Desvinculação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "400":
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Usuário não autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Conta Google não encontrada para desvincular
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/me:
    get:
      summary: Obter dados do usuário autenticado
      description: |
        Retorna informações do usuário atualmente autenticado,
        incluindo dados de integração Google se disponível.
      tags:
        - Authentication
        - User
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Dados do usuário
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
                      email:
                        type: string
                        example: "usuario@exemplo.com"
                      name:
                        type: string
                        example: "João Silva"
                      avatar:
                        type: string
                        example: "https://lh3.googleusercontent.com/..."
                      google_linked:
                        type: boolean
                        example: true
                      email_verified:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-01-01T10:00:00Z"
        "401":
          description: Usuário não autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

security:
  - BearerAuth: []

tags:
  - name: Authentication
    description: Endpoints de autenticação e autorização
  - name: OAuth
    description: Integração com provedores OAuth externos
  - name: User
    description: Operações relacionadas ao usuário autenticado
