@startuml Criação de Novo Usuário
title Criação de Novo Usuário

actor "Administrador" as A
participant "Sistema" as S
participant "User Model" as UM
database "Banco de Dados" as DB

A -> S: Solicita criação de novo usuário
S -> UM: create(UserEntity)
UM -> DB: Inicia transação
UM -> DB: Insere novo usuário
DB --> UM: Confirma inserção
UM --> S: Retorna resultado da criação
S --> A: Confirma criação do usuário
@enduml
