<?php

return [ 
    'others'              => 'Outros',
    'lawyer'              => 'Advogado',
    'architect'           => 'Arquiteto',
    'artist'              => 'Artista',
    'biologist'           => 'Biólogo',
    'chef'                => 'Chef de Cozinha',
    'scientist'           => 'Cientista',
    'political_scientist' => 'Cientista Político',
    'accountant'          => 'Contador',
    'consultant'          => 'Consultor',
    'dentist'             => 'Dentista',
    'designer'            => 'Designer',
    'economist'           => 'Economista',
    'nurse'               => 'Enfermeiro',
    'engineer'            => 'Engenheiro',
    'writer'              => 'Escritor',
    'it_specialist'       => 'Especialista em TI',
    'pharmacist'          => 'Farmacêutico',
    'physicist'           => 'Físico',
    'historian'           => 'Historiador',
    'journalist'          => 'Jornalista',
    'linguist'            => 'Linguista',
    'mathematician'       => 'Matemático',
    'doctor'              => 'Médico',
    'musician'            => 'Músico',
    'pilot'               => 'Piloto',
    'teacher'             => 'Professor',
    'psychologist'        => 'Psicólogo',
    'psychiatrist'        => 'Psiquiatra',
    'geologist'           => 'Geólogo',
    'sociologist'         => 'Sociólogo',
    'technician'          => 'Técnico',
    'veterinarian'        => 'Veterinário'
];
